"""add phone number

Revision ID: 09349b3aa4d4
Revises: 9e513fa36b80
Create Date: 2022-06-04 11:20:56.684292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09349b3aa4d4'
down_revision = '9e513fa36b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
